# Generated by Django 4.0.2 on 2022-10-23 18:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255, unique=True)),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
                ('rank', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=20)),
            ],
        ),
    ]
