# Generated by Django 4.0.2 on 2022-10-23 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_website', '0002_rename_username_user_name_user_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_and_number',
            field=models.CharField(default='test2', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='test3', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='test4', max_length=9, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'.", regex='^\\+?1?\\d{9,9}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.CharField(default='test5', max_length=6, validators=[django.core.validators.RegexValidator(message='Zip code format must be in the format: XX-XXX or XXXXX or XX XXX.', regex='^\\d{2}(?:[-\\s]\\d{3})?$')]),
            preserve_default=False,
        ),
    ]
