# Generated by Django 4.0.2 on 2022-11-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_website', '0005_wine_alter_user_zip_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='WineImage',
            fields=[
                ('file_name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='wines')),
            ],
        ),
    ]
