# Generated by Django 4.0.2 on 2022-11-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_website', '0006_wineimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WineImage',
        ),
        migrations.AddField(
            model_name='wine',
            name='image',
            field=models.ImageField(default='dead', upload_to='wines'),
            preserve_default=False,
        ),
    ]
