# Generated by Django 4.0.2 on 2022-11-10 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_website', '0008_wine_aroma_wine_color_wine_falvor_wine_in_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wine',
            old_name='falvor',
            new_name='flavor',
        ),
    ]
