# Generated by Django 4.0.2 on 2022-11-10 22:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_website', '0009_rename_falvor_wine_flavor'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='size',
            field=models.PositiveIntegerField(default=250, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wine',
            name='vol',
            field=models.PositiveIntegerField(default=13, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
