# Generated by Django 4.0.2 on 2022-11-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_website', '0010_wine_size_wine_vol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='vol',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
