# Generated by Django 4.0.2 on 2022-11-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_website', '0011_alter_wine_vol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='image',
            field=models.ImageField(null=True, upload_to='wines'),
        ),
    ]
