# Generated by Django 4.0.2 on 2022-11-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_website', '0012_alter_wine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='image',
            field=models.ImageField(default='none', upload_to='wines'),
            preserve_default=False,
        ),
    ]
