# Generated by Django 4.0.2 on 2022-11-13 17:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_website', '0013_alter_wine_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordering_website.user')),
                ('wine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordering_website.wine')),
            ],
        ),
    ]
