# Generated by Django 4.0.2 on 2022-11-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_website', '0015_rename_author_id_rating_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
