# Generated by Django 4.0.2 on 2022-11-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_website', '0016_rating_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
