# Generated by Django 4.0.2 on 2022-11-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_website', '0017_alter_rating_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
