# Generated by Django 4.0.2 on 2022-11-16 00:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_website', '0020_alter_rating_description_alter_wine_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address_and_number',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=9, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'.", regex='^\\+?1?\\d{9,9}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(default='', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='zip_code',
            field=models.CharField(default='', max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='Zip code format must be in the format: XX-XXX.', regex='\\d{2}-\\d{3}')]),
        ),
    ]
