# Generated by Django 4.0.2 on 2022-11-16 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_website', '0021_alter_user_address_and_number_alter_user_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_set', to='ordering_website.user'),
        ),
    ]
