# Generated by Django 4.0.2 on 2022-12-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_website', '0025_orderdata_orderedproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdata',
            name='password',
        ),
        migrations.RemoveField(
            model_name='orderdata',
            name='registration_time',
        ),
        migrations.AddField(
            model_name='orderdata',
            name='delivery',
            field=models.CharField(choices=[('courier', 'Courier'), ('parcel_locker', 'Parcel Locker')], default='courier', max_length=20),
        ),
        migrations.AddField(
            model_name='orderdata',
            name='payment',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('paypal', 'Paypal')], default='transfer', max_length=20),
        ),
        migrations.AddField(
            model_name='orderdata',
            name='status',
            field=models.CharField(choices=[('courier', 'Ordered'), ('paid', 'Paid'), ('sent', 'Sent'), ('delivered', 'Delivered')], default='courier', max_length=20),
        ),
    ]
