# Generated by Django 4.0.2 on 2022-12-03 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_website', '0026_remove_orderdata_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdata',
            name='rank',
        ),
    ]
