# Generated by Django 4.0.2 on 2022-12-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_website', '0027_remove_orderdata_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdata',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('paid', 'Paid'), ('sent', 'Sent'), ('delivered', 'Delivered')], default='ordered', max_length=20),
        ),
    ]
