# Generated by Django 4.0.2 on 2022-12-03 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_website', '0028_alter_orderdata_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdata',
            name='address_and_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='phone_number',
            field=models.CharField(default='', max_length=9, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999'.", regex='^\\+?1?\\d{9,9}$')]),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='surname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='zip_code',
            field=models.CharField(default='', max_length=6, validators=[django.core.validators.RegexValidator(message='Zip code format must be in the format: XX-XXX.', regex='\\d{2}-\\d{3}')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_and_number',
            field=models.CharField(default='', max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Adress and number must be in the format: Street 1.', regex='^[a-zA-Z]+?\\s\\w+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=9, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999'.", regex='^\\+?1?\\d{9,9}$')]),
        ),
    ]
