# Generated by Django 4.0.2 on 2022-12-03 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_website', '0029_alter_orderdata_address_and_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdata',
            name='address_and_number',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator(message='Adress and number must be in the format: Street 1.', regex='^[a-zA-Z]+?\\s\\w+$')]),
        ),
    ]
