# Generated by Django 4.0.2 on 2022-12-03 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_website', '0031_alter_orderdata_address_and_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='order_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
