# Generated by Django 4.0.2 on 2022-12-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_website', '0032_orderdata_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdata',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
    ]
