# Generated by Django 4.0.2 on 2022-12-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_website', '0033_alter_orderdata_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='full_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=12),
            preserve_default=False,
        ),
    ]
